# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml

network:
  
system_health:

recorder: 
  auto_purge: true
  purge_keep_days: 5
  
zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 10
  icon: mdi:home

# Text to speech
tts:
  - platform: google_translate
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list binary_sensor

sun:
      
frontend:
  themes: !include_dir_merge_named themes
  
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

octoprint:
  - host: !secret octoprint_url
    api_key: !secret octoprint_api
    name: Ender 5 Plus
    bed: true
    number_of_tools: 1
    sensors:
      monitored_conditions:
        - 'Current State'
        - 'Temperatures'
        - 'Job Percentage'
        - 'Time Elapsed'
        - 'Time Remaining'

# Example configuration.yaml entry
light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedroomlamp
      - light.whitebulb

stream:

# spotify integration
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

### Imported from thejeffreystone github
ssdp:

zeroconf:

mobile_app:

person:

cloud:

conversation:

discovery:

template:
  - binary_sensor:
    - name: lightning_detected
      unique_id: lightning_detected_sensor
      state: >
        {{ states('sensor.recent_lightining_strikes') | int > 0 }}
      device_class: safety

updater:
  include_used_components: true

map:
